### ISSUE TITLE
Uncaught ReferenceError: linesAdded is not defined

### ISSUE THREAD

**Issue by janosimas** [Yu1989/atom-tomatimer#18]
[Enter steps to reproduce below:]

When finishing the work interval this error appears,
last minute message appears fine.

**Atom Version**: 1.7.4
**System**: Ubuntu 14.04.4
**Thrown From**: [tomatimer](https://github.com/Yu1989/atom-tomatimer) package, v1.2.2

### Stack Trace

Uncaught ReferenceError: linesAdded is not defined

```
At /home/jsimas/.atom/packages/tomatimer/lib/tomatimer.js:181

ReferenceError: linesAdded is not defined
  at Object._break [as break] (/home/jsimas/.atom/packages/tomatimer/lib/tomatimer.js:240:24)
  at Timer.<anonymous> (/home/jsimas/.atom/packages/tomatimer/lib/tomatimer.js:74:28)
  at emitNone (events.js:67:13)
  at Timer.emit (events.js:166:7)
  at /home/jsimas/.atom/packages/tomatimer/lib/timer.js:76:22

```

### Commands

```
     -2:15.9.0 core:select-up (atom-text-editor.editor.is-focused)
     -2:15.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:15.2.0 core:delete (atom-text-editor.editor.is-focused)
  2x -2:14.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:14.3.0 core:select-up (atom-text-editor.editor.is-focused)
     -2:13.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:13.4.0 core:delete (atom-text-editor.editor.is-focused)
  2x -2:13.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:12.6.0 core:select-up (atom-text-editor.editor.is-focused)
     -2:11.9.0 core:delete (atom-text-editor.editor.is-focused)
     -2:11.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:10.7.0 core:select-up (atom-text-editor.editor.is-focused)
     -2:10.5.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:09.9.0 core:delete (atom-text-editor.editor.is-focused)
     -2:09.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:03.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter-clang"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.64.0
build-cmake, v0.4.0
busy, v0.5.0
file-type-icons, v1.3.0
formatter, v2.12.3
formatter-astyle, v1.0.0
git-log, v0.4.1
git-plus, v5.14.0
highlight-selected, v0.11.2
language-cmake, v0.1.4
language-cpp14, v0.6.1
language-pgsql, v0.2.3
language-qtpro, v0.6.0
language-valgrind, v0.1.0
linter, v1.11.4
nuclide, v0.139.0
open-recent, v5.0.0
tabasco, v0.5.0
terminal-plus, v0.14.5
tomatimer, v1.2.2

# Dev
No dev packages
```

**Comment by Yu1989** [comment]
@janosimas Thanks for the bug report! I'll look into that. Meanwhile, you can try re-installing tomatimer as a temporary fix.

**Comment by janosimas** [comment]
The tomatimer is working, I just get an error on timer finish.

re-installing didn't fix this.

**Comment by Yu1989** [comment]
@janosimas Should be fixed now. Let me know if there are still issues :)

**Comment by janosimas** [comment]
It's working fine, now.
thanks
